"""timestamps

Revision ID: 94031567e9ea
Revises: efd96e37ee7d
Create Date: 2018-06-30 23:41:32.994640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94031567e9ea'
down_revision = 'efd96e37ee7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_part', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_car_part_timestamp'), 'car_part', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_part_timestamp'), table_name='car_part')
    op.drop_column('car_part', 'timestamp')
    # ### end Alembic commands ###
