"""empty message

Revision ID: d38548e0dbb0
Revises: 94031567e9ea
Create Date: 2018-07-04 23:54:40.339930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38548e0dbb0'
down_revision = '94031567e9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_part', sa.Column('description', sa.String(length=140), nullable=True))
    op.add_column('car_part', sa.Column('image_url', sa.String(length=124), nullable=True))
    op.drop_index('ix_car_part_name', table_name='car_part')
    op.create_unique_constraint(None, 'car_part', ['name'])
    op.drop_column('car_part', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_part', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_constraint(None, 'car_part', type_='unique')
    op.create_index('ix_car_part_name', 'car_part', ['name'], unique=1)
    op.drop_column('car_part', 'image_url')
    op.drop_column('car_part', 'description')
    # ### end Alembic commands ###
